 INSERT INTO CAR_MARK (ID, NAME) VALUES (1, 'MERCEDES');
 INSERT INTO CAR_MARK (ID, NAME) VALUES (2, 'AUDI');
 INSERT INTO CAR_MARK (ID, NAME) VALUES (3, 'BMW');
 INSERT INTO CAR_MARK (ID, NAME) VALUES (4, 'VW');
 INSERT INTO CAR_MARK (ID, NAME) VALUES (5, 'FIAT');
 INSERT INTO CAR_MARK (ID, NAME) VALUES (6, 'FORD');

 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (1, 1, 'CLA' );
 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (2, 1, 'C CLASS' );
 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (3, 1, 'S CLASS' );
 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (4, 2, 'A6' );
 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (5, 2, 'A7' );
 INSERT INTO CAR_MODEL (ID, CAR_MARK_ID, NAME) VALUES (6, 3, 'M4' );


 INSERT INTO CAR (ID, CAR_MODEL_ID, COLOR, PRICE) VALUES (1, 1, 'BLACK', 150000 );
 INSERT INTO CAR (ID, CAR_MODEL_ID, COLOR, PRICE) VALUES (2, 3, 'WHITE', 350000 );
 INSERT INTO CAR (ID, CAR_MODEL_ID, COLOR, PRICE) VALUES (3, 4, 'WHITE', 250000 );
 INSERT INTO CAR (ID, CAR_MODEL_ID, COLOR, PRICE) VALUES (4, 6, 'YELLOW', 450000 );





